services:
  # Backend FastAPI
  backend:
    build:
      context: ./cortex_back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - ENVIRONMENT=production
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      # Base de datos de autenticación
      - ./cortex_back/data:/app/data
      # Datos OMOP completos (CSV, DB, índices FAISS)
      - ./cortex_back/app/OMOP_SNOMED:/app/OMOP_SNOMED
      # Base de datos de testing OMOP
      - ./cortex_back/omop_testing:/app/omop_testing
      # Índices RAG (si tienes más cosas por aquí)
      - ./cortex_back/rag_index:/app/rag_index
      # Cache de modelos (opcional)
      - ./cortex_back/model_cache:/app/model_cache
    depends_on:
      - ollama
    networks:
      - cortex-network

  # Frontend React
  frontend:
    build:
      context: ./cortex_app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cortex-network

  # Ollama para LLMs
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    networks:
      - cortex-network
    # Si tienes GPU disponible
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - cortex-network

volumes:
  ollama_data:

networks:
  cortex-network:
    driver: bridge